config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :automotoras

  resources :usuarios

  get 'welcome/index'

  root 'welcome#index'

end

app/models/automotora.rb
class Automotora < ActiveRecord::Base
  belongs_to :usuario
  validates :codigo, presence: true
  validates :marca, presence: true
  validates :precio, presence: true
  validates :modelo, presence: true
  validates :color, presence: true
  scope :recientes, ->{order("created_at desc")}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/automotoras_controller.rb
class AutomotorasController < ApplicationController
  before_action :set_automotora, only: [:show, :edit, :update, :destroy]

  # GET /automotoras
  # GET /automotoras.json
  def index
    @automotoras = Automotora.recientes.all
  end

  # GET /automotoras/1
  # GET /automotoras/1.json
  def show
  end

  # GET /automotoras/new
  def new
    @automotora = Automotora.new
  end

  # GET /automotoras/1/edit
  def edit
  end

  # POST /automotoras
  # POST /automotoras.json
  def create
    @automotora = Automotora.new(automotora_params)

    respond_to do |format|
      if @automotora.save
        format.html { redirect_to @automotora, notice: 'Automotora was successfully created.' }
        format.json { render :show, status: :created, location: @automotora }
      else
        format.html { render :new }
        format.json { render json: @automotora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automotoras/1
  # PATCH/PUT /automotoras/1.json
  def update
    respond_to do |format|
      if @automotora.update(automotora_params)
        format.html { redirect_to @automotora, notice: 'Automotora was successfully updated.' }
        format.json { render :show, status: :ok, location: @automotora }
      else
        format.html { render :edit }
        format.json { render json: @automotora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automotoras/1
  # DELETE /automotoras/1.json
  def destroy
    @automotora.destroy
    respond_to do |format|
      format.html { redirect_to automotoras_url, notice: 'Automotora was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automotora
      @automotora = Automotora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def automotora_params
      params.require(:automotora).permit(:codigo, :marca, :precio, :modelo, :color, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :correo, :edad)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/automotoras_helper.rb
module AutomotorasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/automotoras/_form.html.erb
<%= form_for(@automotora) do |f| %>
  <% if @automotora.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@automotora.errors.count, "error") %> prohibited this automotora from being saved:</h2>

      <ul>
      <% @automotora.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.select( "usuario_id",Usuario.all.collect{|l| [ l.nombre, l.id ] }, {include_blanck: 'seleccione Usuario'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/automotoras/edit.html.erb
<h1>Editing automotora</h1>

<%= render 'form' %>

<%= link_to 'Show', @automotora %> |
<%= link_to 'Back', automotoras_path %>

app/views/automotoras/index.html.erb
<h1>Listing automotoras</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Marca</th>
      <th>Precio</th>
      <th>Modelo</th>
      <th>Color</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @automotoras.each do |automotora| %>
      <tr>
        <td><%= automotora.codigo %></td>
        <td><%= automotora.marca %></td>
        <td><%= automotora.precio %></td>
        <td><%= automotora.modelo %></td>
        <td><%= automotora.color %></td>
        <td><%= automotora.usuario.nombre %></td>
        <td><%= link_to 'Show', automotora %></td>
        <td><%= link_to 'Edit', edit_automotora_path(automotora) %></td>
        <td><%= link_to 'Destroy', automotora, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Automotora', new_automotora_path %>

app/views/automotoras/new.html.erb
<h1>New automotora</h1>

<%= render 'form' %>

<%= link_to 'Back', automotoras_path %>

app/views/automotoras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @automotora.codigo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @automotora.marca %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @automotora.precio %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @automotora.modelo %>
</p>

<p>
  <strong>Color:</strong>
  <%= @automotora.color %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @automotora.usuario.nombre %>
</p>

<%= link_to 'Edit', edit_automotora_path(@automotora) %> |
<%= link_to 'Back', automotoras_path %>

app/views/cargamenu/_alert.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/cargamenu/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><a href="<%= usuarios_path %>">Usuarios</a></li>
          <li><a href="<%= automotoras_path %>">Automotoras</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a> <%= current_user.email %> </a></li>
        	<li><a href="<%= edit_user_registration_path(current_user) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_user_session_path %>", data-method="delete">Cerrar Sesión</a></li>
        <% else %>
        	<li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
        	<li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS --> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> <!-- Optional theme --> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"> <!-- Latest compiled and minified JavaScript --> <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>

  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <%= render 'cargamenu/alert' %>
   <%= render 'cargamenu/navbar' %>

<%= yield %>

</body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :edad %><br>
    <%= f.number_field :edad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.edad %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @usuario.edad %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>